version: '3.8'

services:
  web:
    build: ./app
    container_name: historia_web
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - bfa-node  # 👈 importante
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=hc_bfa
      - PRIVATE_KEY_BFA=03ca4edb5fb0dff310f92f8421cfbb1f3b5b2bb54ac9b9e3314b133fb7daae2b
      - ADDRESS_BFA=0xa2f22ad8781170145406a8c3dc69701e1fe16f7d
    command: flask run
    networks:
      - historia_net

  db:
    image: mysql:8.0
    container_name: historia_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hc_bfa
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - historia_net

  bfa-node:
    image: ubuntu:20.04
    container_name: bfa-node
    ports:
      - "8545:8545"
    volumes:
      - ./bfa-node/nucleo:/nucleo
      - ./bfa-node/container/setup_bfa_node.sh:/setup_bfa_node.sh
    command: bash /setup_bfa_node.sh
    networks:
      - historia_net

networks:
  historia_net:

volumes:
  db_data:
